version: "3.9"

services:
  app:
    container_name: monitoring-service
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379"
    networks:
      - net

networks:
  net:
    name: net